KEEP_COLs = ["responseN",
             "participant",
             "blockOrder",
             "age",
             "sex",
             "date",
             "frameRate",
             "imageFile",
             "trials.thisN",
             "index"
             "trials.thisIndex",
             "blocks.thisN",
             "blocks.thisIndex",
             "winsize",
             "numerosity",
             "perceptpairs",
             "protectzonetype",
             "convexhull",
             "occupancyarea",
             "averageeccentricity",
             "averagespacing",
             "density",
             "display_i"]

